# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    build:
      dockerfile: docker/db.Dockerfile
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password

  app:
    depends_on:
      - db
    build:
      dockerfile: docker/app.Dockerfile
    environment:
      DATABASE_HOST: db
    ports:
      - "8000:8000"
    restart: always
